#!/bin/bash
cd "$(dirname "$0")"
trap "exit" SIGHUP SIGINT SIGTERM
data=$(tempfile 2>/dev/null)
while true; do
	whiptail --inputbox "Wat is het ID van deze container?" 10 40 $(cat id) 2>$data
	geupdate=$?
	if [ $geupdate -eq 0 ]; then
		mv $data id
	fi
	whiptail --inputbox "Wat is de maximale afstand in CM?\nOp dit moment is de afstand\n$(./cscript)cm." 10 40 $(cat afstand) 2>$data
	geupdate=$?
	if [ $geupdate -eq 0 ]; then
		mv $data afstand
	fi
	sync
	whiptail --msgbox "Dit zijn de instellingen:\nID: $(cat id)\nafstand: $(cat afstand)\ndoe de pi in de container." 10 40
done
