#!/bin/bash
cd "$(dirname "$0")"
trap "exit" SIGHUP SIGINT SIGTERM
while true; do
	whiptail --inputbox "Voer een nieuw ID in." 8 40 2>newid
	geupdate=$?
	if [ $geupdate -eq 0 ]; then
		mv newid id
		sync
		whiptail --msgbox "De instellingen zijn opgeslagen.\n doe de pi in de container." 8 40
	else
		rm newid
		sync
		whiptail --msgbox "De instellingen zijn niet opgeslagen.\n Begin opnieuw." 8 40
	fi
done
