#!/bin/bash
cd "$(dirname "$0")"
containerId=$(cat id)
echo "containerId: $containerId"
maxAfstand=$(cat afstand)
echo "max afstand: $maxAfstand"
huidigeAfstand=$(./cscript) #cscript is afkomstig van https://github.com/OmarAflak/HC-SR04-Raspberry-Pi-C-
echo "huidige afstand: $huidigeAfstand"
percentage=$(echo "100*($maxAfstand-$huidigeAfstand)/$maxAfstand" | bc)
echo "percentage: $percentage"
curl -d '{"id":"'$containerId'","inhoud":"'$percentage'"}' -H 'Content-Type: application/json' -X POST https://afval.rubend.nl/nodejs
